package main

import (
  "os"
  "text/template"
  "encoding/csv"
)

func main() {
  f, err := os.Open("../../palette/black-white-grey.csv")
  if err != nil { panic(err) }
  defer f.Close()

  // convert dmc data to csv hash
  reader := csv.NewReader(f)
  reader.Comma = ','
  record, err := reader.ReadAll()
  if err != nil { panic(err) }

  out, err := os.Create("consts.go")
  if err != nil { panic(err) }
  defer out.Close()

  pkgTmpl := template.Must(template.New("").Parse(`// Code generated by Go generate. DO NOT EDIT
package main

type Thread struct {
  Floss int
  Name string
  R int
  G int
  B int
}

BWGColors = []Thread {
  {{ range record := .Records }}
    Thread {
      Floss: {{ record[0] }},
      Name: "{{ record[1] }}",
      R: {{ record[2] }},
      G: {{ record[3] }},
      B: {{ record[4] }}
    },
}
`))

  pkgTmpl.Execute(out, struct {
    Records [][]string
  }{
    Records: record,
  })
}
