name: Lint and Test App

on: push

jobs:
  lint:
    name: Lint and Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.18"
          cache: false

      - name: Run go fmt
        run: test -z $(gofmt -l .)

          #- name: Run golangci-lint
          #uses: golangci/golangci-lint-action@v3
          #with:
          #version: v1.29

      - name: Run go get
        run: go get

      - name: Run go vet
        run: go vet -all ./...

      - name: Test app
        run: go test ./...
